name: Integration Smoke Test

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  smoke:
    name: Smoke test (container health)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull image
        run: |
          # Pull the unified image published by CI (latest)
          docker pull ghcr.io/tekgnosis-net/pdfkb-mcp:latest || true

      - name: Start container (CPU embeddings)
        run: |
          docker run -d --name pdfkb-smoke -p 9000:8000 \
            -e PDFKB_EMBEDDING_DEVICE=cpu \
            ghcr.io/tekgnosis-net/pdfkb-mcp:all

      - name: Wait for /health (up to 2 minutes)
        run: |
          set -euo pipefail
          for i in $(seq 1 60); do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/health || echo "")
            echo "Attempt $i: status=$status"
            if [ "$status" = "200" ]; then
              echo "health ok"
              exit 0
            fi
            sleep 2
          done
          echo "Service did not become healthy in time"
          docker logs pdfkb-smoke || true
          exit 1

      - name: Run a basic API smoke (status)
        run: |
          curl -sS http://localhost:9000/api/status || true

      - name: Parser import checks
        run: |
          set -euo pipefail
          CONTAINER=pdfkb-smoke
          parsers=("docling" "marker" "mineru" "pymupdf4llm")
          for p in "${parsers[@]}"; do
            echo "Checking parser target /opt/parsers/$p importability"
            docker exec ${CONTAINER} sh -c "python3 - <<'PY'
              import sys
              target = '/opt/parsers/' + '${p}'
              if target not in sys.path:
                  sys.path.insert(0, target)
              try:
                  __import__('${p}')
                  print('OK: imported ${p}')
              except Exception as e:
                  import traceback
                  traceback.print_exc()
                  sys.exit(2)
            PY"
            echo "Parser ${p} import returned: $?"
          done

      - name: Teardown
        if: always()
        run: |
          docker rm -f pdfkb-smoke || true
