name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install the package with developer extras (fast and reliable).
          # Then attempt to install a small set of optional packages that
          # tests commonly import during collection. Make those installs
          # non-fatal so runners that can't build heavy native deps still
          # run the test suite (tests should stub heavy libraries where
          # appropriate).
          python -m pip install -e '.[dev]' \
            && python -m pip install whoosh langchain-core aiohttp reportlab marker-pdf || true

      - name: Run tests
        run: |
          pytest -q
