name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install the package and developer extras (falls back to editable install)
          python -m pip install -e '.[dev]' || python -m pip install -e .

      - name: Run tests
        run: |
          pytest -q
